In [1]:
import numpy as np
import random

In [2]:
random.seed(42)

lst1 = [random.randint(10, 100) for _ in range(5)]
lst2 = [random.randint(10, 100) for _ in range(5)]
lst3 = [random.randint(10, 100) for _ in range(5)]
lst4 = [random.randint(10, 100) for _ in range(5)]
lst5 = [random.randint(10, 100) for _ in range(5)]

print(lst1, lst2, lst3)

[91, 24, 13, 45, 41] [38, 27, 23, 96, 79] [21, 85, 64, 14, 13]


In [3]:
twodarray = np.array([lst1, lst2, lst3, lst4, lst5], dtype = int)

twodarray

array([[91, 24, 13, 45, 41],
       [38, 27, 23, 96, 79],
       [21, 85, 64, 14, 13],
       [21, 37, 39, 74, 87],
       [13, 81, 35, 93, 99]])

In [4]:
# Traverse the array using a for loop

def traverse(array):
    for idx, row in enumerate(array): 
        for idx, ele in enumerate(row): 
            print(ele, end = " ")
        print()

traverse(twodarray)

91 24 13 45 41 
38 27 23 96 79 
21 85 64 14 13 
21 37 39 74 87 
13 81 35 93 99 


In [5]:
# Two Dimensional array insertion
column = [random.randint(10, 100) for _ in range(5)]
print(column, '\n')

# insert a column
twodarray = np.insert(twodarray, 0, column, axis=1)
twodarray

row = [random.randint(10, 100) for _ in range(6)]
print(row, '\n')

# insert a row
twodarray = np.insert(twodarray, 0, row, axis=0)
twodarray

# inserting elements at the end using the append() method\
row = [random.randint(10, 100) for _ in range(6)]
print(row, '\n')

print(twodarray)

twodarray = np.append(twodarray, [row], axis=0)
twodarray

[79, 63, 38, 67, 85] 

[45, 10, 30, 99, 64, 53] 

[45, 29, 37, 53, 23, 21] 

[[45 10 30 99 64 53]
 [79 91 24 13 45 41]
 [63 38 27 23 96 79]
 [38 21 85 64 14 13]
 [67 21 37 39 74 87]
 [85 13 81 35 93 99]]


array([[45, 10, 30, 99, 64, 53],
       [79, 91, 24, 13, 45, 41],
       [63, 38, 27, 23, 96, 79],
       [38, 21, 85, 64, 14, 13],
       [67, 21, 37, 39, 74, 87],
       [85, 13, 81, 35, 93, 99],
       [45, 29, 37, 53, 23, 21]])

In [ ]:
# Delete a row or column 

# delete a row, change axis to 1 to delete column
twodarray = np.delete(twodarray, 0, axis=0)
twodarray

array([[93, 99],
       [23, 21]])